"""empty message

Revision ID: bbcb283b7008
Revises: 0763d677d453
Create Date: 2025-05-13 18:15:25.948570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcb283b7008'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('connection_method', sa.String(length=20), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alpr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('left_pos', sa.Integer(), nullable=True),
    sa.Column('top_pos', sa.Integer(), nullable=True),
    sa.Column('right_pos', sa.Integer(), nullable=True),
    sa.Column('bottom_pos', sa.Integer(), nullable=True),
    sa.Column('char_height', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('multiplate', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_color', sa.String(length=20), nullable=True),
    sa.Column('vehicle_model', sa.String(length=50), nullable=True),
    sa.Column('vehicle_make', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('alpr_records')
    op.drop_table('users')
    op.drop_table('cameras')
    # ### end Alembic commands ###
